export { default as Hero } from "./Hero";
export { default as Gallery } from "./Gallery";
export { default as Video } from "./Video";
export { default as Bookings } from "./Bookings";
export { default as Mixes } from "./Mixes";
export { default as About } from "./About";
export { default as Services } from "./Services";
export { default as CTA } from "./CTA";
export { default as Footer } from "./Footer";
